### ISSUE TITLE
Use posix_spawnp() instead of fork()/exec()

### ISSUE THREAD

**Issue by shawnw** [rajatjain1997/subprocess#12]
Mainly because [`posix_spawnp()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_spawn.html) is conceptually closer to the WIn32 [`CreateProcess()`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa) model, and it might make porting to Windows easier if the WIndows and Unix workflows are basically the same.

**Comment by rajatjain1997** [comment]
Thanks for the suggestion! This is merged.
