### ISSUE TITLE
File descriptors are opened during command creation

### ISSUE THREAD

**Issue by rajatjain1997** [rajatjain1997/subprocess#4]
Currently, file descriptors are opened when the command is being built. i.e.

    command{"ls"} | command{"cat"};

would actually open a pipe even though the command has not been run. If the command never runs, these pipes will never be closed. Change it so that pipes are only opened when the commands are being executed.

**Comment by shawnw** [comment]
As long as the descriptors are closed in the command's destructor, that shouldn't be a big deal.

**Comment by rajatjain1997** [comment]
Yeah you're right. Open FDs however make the command object non-trivially copyable as well.

**Comment by rajatjain1997** [comment]
All I/Os are now modelled as a descriptor. Users can inherit `idescriptor`, `odescriptor`, or `descriptor` class to provide their own functionalities for reading from OS pipe file descriptors.
`open()` is called on the object right before posix_spawn
`close()` is called after the spawn is done.
`fd()` is closed and duped by the process.
